// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4p4m8MKb-XbEbfR8Bm6zIaL4XVHvB88k',
    appId: '1:346221517030:web:502038ffb4be14ef9f0327',
    messagingSenderId: '346221517030',
    projectId: 'mahasiswa-app-e50bc',
    authDomain: 'mahasiswa-app-e50bc.firebaseapp.com',
    databaseURL: 'https://mahasiswa-app-e50bc-default-rtdb.firebaseio.com',
    storageBucket: 'mahasiswa-app-e50bc.appspot.com',
    measurementId: 'G-5PC5P6XF74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1amtfOBOxeLeKkYqYh-n15JFyFareHJg',
    appId: '1:346221517030:android:98445e19552a48699f0327',
    messagingSenderId: '346221517030',
    projectId: 'mahasiswa-app-e50bc',
    databaseURL: 'https://mahasiswa-app-e50bc-default-rtdb.firebaseio.com',
    storageBucket: 'mahasiswa-app-e50bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARXIcYQ9lsvkHr8wVb6xquisLjI9X4vBw',
    appId: '1:346221517030:ios:6ac1e2263c2ae32d9f0327',
    messagingSenderId: '346221517030',
    projectId: 'mahasiswa-app-e50bc',
    databaseURL: 'https://mahasiswa-app-e50bc-default-rtdb.firebaseio.com',
    storageBucket: 'mahasiswa-app-e50bc.appspot.com',
    iosBundleId: 'com.example.daftarMahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARXIcYQ9lsvkHr8wVb6xquisLjI9X4vBw',
    appId: '1:346221517030:ios:6a4841e7ce8c77ad9f0327',
    messagingSenderId: '346221517030',
    projectId: 'mahasiswa-app-e50bc',
    databaseURL: 'https://mahasiswa-app-e50bc-default-rtdb.firebaseio.com',
    storageBucket: 'mahasiswa-app-e50bc.appspot.com',
    iosBundleId: 'com.example.daftarMahasiswa.RunnerTests',
  );
}
